### ISSUE TITLE
Suggestion - Optional split for a more managable list. 

### ISSUE THREAD

**Issue by VeloxAzo** [Creeper37500-da-Snek/UniversalCrafter#1]
I love this mod, the statues and furniture seem a bit excessive at times though. 

I propose adding two additional crafters to the mod - one that contains none of the miscellaneous furniture/cosmetic crafting benches, and one that only contains them.

**Comment by Antirhinnum** [comment]
The mod has been updated to v1.5, making the Tile List cycle through five categories instead of displaying all the tiles at once. I hope this helps.
